library identifier: 'yanolja-pipeline-library', changelog: false
 
publishComPipeline containers: [
            [
                name: 'helm'
            ]
        ], {
    publishHelm script: 'cd charts/tyk/tyk-pro'
}